# clarifies all of the info needed for each metric

from sqlalchemy import Column, Integer, Float, String, Boolean, DateTime, Date, UniqueConstraint
from datetime import datetime
from app.database import Base


# For automated Apple Watch records
class BiometricStream(Base):

    __tablename__ = "biometrics"

    id = Column(Integer, primary_key=True, index=True)
    timestamp = Column(DateTime, nullable=False)
    # HRV, Resting Heart Rate, Sleep Quality Index, Steps, etc.
    metric_type = Column(String, nullable=False)
    # ensures all data is a float
    value = Column(Float, nullable=False)

    # prevents duplicate rows when the app re-syncs the same reading
    # (same metric at the same timestamp = same data point)
    __table_args__ = (
        UniqueConstraint("timestamp", "metric_type", name="uq_biometric_timestamp_metric"),
    )


# For manual daily user symptom entries
class CycleLog(Base):

    __tablename__ = "cycle_logs"

    # index=True creates an internal sorted reference tree
    # makes for O(log N) rather than O(N) search
    id = Column(Integer, primary_key=True, index=True)
    # unique=True avoids duplicate entries for the same date
    date = Column(Date, unique=True, nullable=False, index=True)
    period_start = Column(Boolean, default=False)
    # 0 = none, 5 = most severe
    abdominal_pain_severity = Column(Integer, default=0)


# Calculated output table -- written by phase_engine.py, read by the dashboard
# Each row represents one calendar date and what the engine computed for it.
class DailyInsight(Base):

    __tablename__ = "daily_insights"

    id = Column(Integer, primary_key=True, index=True)
    # one row per calendar date
    date = Column(Date, unique=True, nullable=False, index=True)

    # which hormonal phase this date falls in, based on cycle history
    # values: "menstrual", "follicular", "ovulatory", "luteal", "unknown"
    cycle_phase = Column(String, nullable=True)
    # day number within the current cycle (1 = first day of period)
    cycle_day = Column(Integer, nullable=True)
    # predicted date of the next period, recalculated each run
    predicted_next_period = Column(Date, nullable=True)

    # per-phase historical averages for each metric
    # these are what power the "your HRV drops 14% in luteal phase" alerts
    hrv_phase_avg = Column(Float, nullable=True)
    rhr_phase_avg = Column(Float, nullable=True)
    sleep_phase_avg = Column(Float, nullable=True)
    steps_phase_avg = Column(Float, nullable=True)

    # overall phase averages across all history (for comparison)
    hrv_overall_avg = Column(Float, nullable=True)
    rhr_overall_avg = Column(Float, nullable=True)
    sleep_overall_avg = Column(Float, nullable=True)
    steps_overall_avg = Column(Float, nullable=True)

    # the human-readable alert text generated by the engine
    # e.g. "⚠️ HRV averages 14% lower in your luteal phase"
    insight_text = Column(String, nullable=True)